version: '3.8'
services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongo
    environment:
      - 'MONGO_INITDB_DATABASE=financial_control'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka-data:/bitnami/kafka

  financial-control:
    build: .
    container_name: financial-control-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - kafka
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:secret@mongodb:27017/financial_control?authSource=admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  akhq:
    image: 'tchiotludo/akhq'
    container_name: akhq
    ports:
      - "8081:8080"
    volumes:
      - ./akhq-config.yml:/app/application.yml
    depends_on:
      - kafka

  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "3000:80"
    depends_on:
      - financial-control

volumes:
  mongo-data:
  kafka-data: